# 1. Numpy stands for?

Answer: Numerical Python

# 2. The most important object defined in Numpy is an N-dimensional array type called?

Answer: ndarray

# 3. What will be output for the following code?

In [1]:
import numpy as np
a = np.array([1, 2, 3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a = np.array([1, 2, 3], dtype ="float")
print(a)

[1. 2. 3.]


In [4]:
a = np.dtype('i4')
print(a)

int32


In [5]:
a = np.array([1, 2, 3,4,5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [6]:
dt = np.dtype([('age', np.int8)])
a = np.array([(10,),(20,),(30,)], dtype = dt)
print(a['age'])

[10 20 30]


In [7]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
print(c)
c = c*a
print (c[2])

[1 5 7 7 9]
21


In [8]:
a = np.array([1,2,3,5,8])
a = a + 1
print (a[1])

3


In [9]:
a = np.array([[1,2,3],[0,1,4]])
print (a.size)

6


In [10]:
a = np.array([1,2,3,5,8])
print (a.ndim)
print (a.shape)
#Errors
print (a.describe)
print (a.ndim.describe)
print (a.shape())


1
(5,)


AttributeError: ignored

In [11]:
a = np.array([[1,2,3],[0,1,4]])
b = np.zeros((2,3), dtype=np.int16)
c = np.ones((2,3), dtype=np.int16)
d = a + b + c
print(d)
print(d[1,2])
print(d.size)
#Errors
print(a.zeroes())

[[2 3 4]
 [1 2 5]]
5
6


AttributeError: ignored

# 4. You have a matrix defined as below:

#### A = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])

In [12]:
A = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
print(f"Rank of the matrix is: {np.linalg.matrix_rank(A)}")
print(f"Determinant of the matrix is: {np.linalg.det(A)}")
print(f"Trace of the matrix is: {np.matrix.trace(A)}")
print(f"Inverse of the matrix is: {np.linalg.inv(A)}")
print(f"Transpose of the matrix is: {np.matrix.transpose(A)}")

Rank of the matrix is: 3
Determinant of the matrix is: -306.0
Trace of the matrix is: 11
Inverse of the matrix is: [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
Transpose of the matrix is: [[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


# 5. Type these lines of code and check the output for each of them.

In [13]:
list1 = [1, 2, 3, 4 ,5, 6]
list2 = [10, 9, 8, 7, 6, 5]

In [14]:
#Will throw error
print(f"Multiplication of Lists: {list1*list2}")
print(f"Addition of Lists: {list1+list2}")
print(f"Modulus of Lists: {list1%list2}")
print(f"Division of Lists: {list1/list2}")
print(f"Subtraction of Lists: {list1-list2}")
print(f"XOR of Lists: {list1^list2}")

TypeError: ignored

# 6. Type these lines of code and check the output for each of them.

In [15]:
list1 = np.array([1, 2, 3, 4 ,5, 6])
list2 = np.array([10, 9, 8, 7, 6, 5])

In [16]:
print(f"Multiplication of Lists: {list1*list2}")
print(f"Addition of Lists: {list1+list2}")
print(f"Modulus of Lists: {list1%list2}")
print(f"Division of Lists: {list1/list2}")
print(f"Subtraction of Lists: {list1-list2}")
print(f"XOR of Lists: {list1^list2}")

Multiplication of Lists: [10 18 24 28 30 30]
Addition of Lists: [11 11 11 11 11 11]
Modulus of Lists: [1 2 3 4 5 1]
Division of Lists: [0.1        0.22222222 0.375      0.57142857 0.83333333 1.2       ]
Subtraction of Lists: [-9 -7 -5 -3 -1  1]
XOR of Lists: [11 11 11  3  3  3]
